### ISSUE TITLE
Add some tables for task management

### ISSUE THREAD

**Issue by chenxidev1129** [chenxidev1129/taskmaster-api#6]
**Comments Table:**
**Id:** INT (Primary Key, Auto-increment)
**UserId:** String (Foreign Key to Users Table)
**TaskId:** INT (Foreign Key to Tasks Table)
**Content:** TEXT or VARCHAR(MAX)
**CreatedAt:** DATETIME
**UpdatedAt:** DATETIME

**Attachments Table:**
**Id:** INT (Primary Key, Auto-increment)
**UserId:** String (Foreign Key to Users Table)
**TaskId:** INT (Foreign Key to Tasks Table)
**FileName:** VARCHAR(255)
**CreatedAt:** DATETIME
**UpdatedAt:** DATETIME

**Tags Table:**
**Id:** INT (Primary Key, Auto-increment)
**Name:** VARCHAR(50)

**Activity Log Table:**
**Id:** INT (Primary Key, Auto-increment)
**UserId:** INT (Foreign Key to Users Table)
**Action:** VARCHAR(100) (Description of the action)
**Timestamp:** DATETIME

**Notifications Table:**
**Id:** INT (Primary Key, Auto-increment)
**UserId:** INT (Foreign Key to Users Table)
**Content:** TEXT or VARCHAR(MAX)
**IsRead:** BOOLEAN (Flag indicating if the notification is read)
**CreatedAt:** DATETIME

**Settings Table:**
**Id:** INT (Primary Key, Auto-increment)
**SettingName:** VARCHAR(100)
**SettingValue:** VARCHAR(MAX) or appropriate type for values
**Description:** TEXT or VARCHAR(MAX) (Optional field for description)

**Comment by chenxidev1129** [comment]
@johnsmith0305 Please check this tickets to enhance our tables for task management

**Comment by johnsmith0305** [comment]
That's good, I agree.
